### PR TITLE
Fix edit to not show full contact/appointment list

### LINKED ISSUE #235: [PE-D] After editing contact from a found list, all contacts are listed again instead of listing only the found contacts.
`find o/email .com`

`edit 1 p/012345`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: oeiyiping/ped#8

### PR DESCRIPTION
**Pull request by nicoleang09**
Resolves #235

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java [hunk 1]
```diff
@@ -82,7 +81,7 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.setAppointment(appointmentToEdit, editedAppointment);
-        model.updateFilteredAppointmentList(PREDICATE_SHOW_ALL_APPOINTMENTS);
+        // model.updateFilteredAppointmentList(PREDICATE_SHOW_ALL_APPOINTMENTS);
```
Comment (edelinetenges) [inline src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java:84]: maybe you can delete the comment since you don't need it anymore?

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -86,7 +85,7 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.setContact(contactToEdit, editedContact);
-        model.updateFilteredContactList(PREDICATE_SHOW_ALL_CONTACTS);
+        // model.updateFilteredContactList(PREDICATE_SHOW_ALL_CONTACTS);
```
Comment (edelinetenges) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:88]: maybe you can delete this comment too

**Review by edelinetenges — APPROVED** [review]
Looks good! Just a few stray comments to be deleted

**Review by clarlzx — APPROVED** [review]
Looks good to be merged! 👍
